apiVersion: v1
kind: Namespace
metadata:
  name: the-dot
  labels:
    app: the-dot
---
apiVersion: v1
kind: Secret
metadata:
  name: the-dot-secrets
  namespace: the-dot
type: Opaque
stringData:
  # Database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: the_dot

  # Redis
  REDIS_PASSWORD: ""

  # RabbitMQ
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin123

  # MinIO
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin

  # JWT Secrets (CHANGE IN PRODUCTION)
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: the-dot-config
  namespace: the-dot
data:
  NODE_ENV: "production"

  # Database URLs
  AUTH_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/auth_db"
  USER_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/user_db"
  APPLICATION_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/application_db"
  TICKET_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ticket_db"
  PROJECT_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/project_db"
  COMMENT_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/comment_db"
  REPORTING_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/reporting_db"
  AUDIT_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/audit_db"

  # Service URLs
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://admin:admin123@rabbitmq:5672"
  MINIO_ENDPOINT: "minio:9000"

  # Inter-service URLs
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  APPLICATION_SERVICE_URL: "http://application-service:3003"
  TICKET_SERVICE_URL: "http://ticket-service:3004"
  PROJECT_SERVICE_URL: "http://project-service:3005"
  COMMENT_SERVICE_URL: "http://comment-service:3006"
  REPORTING_SERVICE_URL: "http://reporting-service:3007"
  AUDIT_SERVICE_URL: "http://audit-service:3008"

  # Frontend
  REACT_APP_API_URL: "http://localhost"
  REACT_APP_WEBSOCKET_URL: "ws://localhost/ws"
